### ISSUE TITLE
update is too slow

### ISSUE THREAD

**Issue by fov42550564** [reapp/reapp#74] opened 2015-05-27 00:42 UTC

**Comment by mbrochh** [comment] 2015-05-27 03:48
@fov42550564 I think it would be helpful if you could provide more details. What are you doing? What exactly is slow? Which devices do you use to test?

**Comment by mbrochh** [comment] 2015-05-27 03:49
Also, this might be a duplicate of: https://github.com/reapp/reapp/issues/18

**Comment by fov42550564** [comment] 2015-05-28 01:05
I mean author update project and answer issue is too slow, i wish reapp is a active project

**Comment by mbrochh** [comment] 2015-05-28 05:34
To be honest, creating an issue complaining that updates are too slow is quite lame. If you don't like it, look for other alternatives, there are plenty (touchstone.js, ionic and many more), or create a fork and solve all issues on your own.

**Comment by mbrookes** [comment] 2015-07-17 20:16
Meaningless issue. Please close.

**Closed** 2015-10-29 05:38 UTC
